target = "https://www.luogu.com.cn/api/discuss?forum=relevantaffairs&page=1"
time_interval = 30

[database]
url = "xxx"

[request]
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36"
cookie = "xxx"

[http]
port = 9000
access_origin = "*"

[functions]
autosave = false
web = true